- unity/Assets/Puerts/Src/JsEnv.cs
- unity/Assets/Puerts/Src/StaticCallbacks.cs
- unity/Assets/Puerts/Src/TypeRegister.cs
[*]Fix StatiCallbacks.cs-->StaticCallbacks.cs
> [*]Fix StatiCallbacks.cs-->StaticCallbacks.cs

- .github/workflows/Windows.yml
- .github/workflows/android.yml
- .github/workflows/ios.yml
- .github/workflows/osx.yml
- .github/workflows/win.yml
自动编译 unity 的动态链接库
需要 unity/native_src/** 目录有改动才会自动编译
> 自动编译 unity 的动态链接库

- unity/Assets/Puerts/Src/Editor/Generator.cs
System.IO下
```
public class StringWriter : TextWriter {
...
}
```
> 基类TextWriter中有5个版本的WriteLineAsync  
> 子类StringWriter中override了其中的3个版本  
优化后的导出行为：
> 如果TextWriter和StringWriter都做了[Typing]导出  
> 新导出方式typing中StringWriter不再包含WriteLineAsync的声明
> 如果只有StringWriter做了[Typing]导出  
> 新导出方式typing中StringWriter仅包含3个WriteLineAsync的声明
FairyGUI下
```
class GObject {
public void InvalidateBatchingState();
}
class GComponent extends GObject {
public void InvalidateBatchingState(bool childChanged);
}
```
由于TypeScript的overload机制的限制，必须在子类中声明全部的签名，否则会遇到ts2416错误
> 新导出方式GComponent下将会有2个版本的InvalidateBatchingState的声明
```cs
static MethodInfo[] GetMethodsForTsTypeGen(Type type, HashSet<Type> genTypeSet)
{
// 过滤DeclaredOnly的方法
//   m.GetBaseDefinition() == m // 非override方法
// …
```
> 优化d.ts的成员函数导出

- unity/Assets/Puerts/Src/MethodReflection.cs
> 修复不定长参数的Bug

- unity/Assets/Puerts/Src/Editor/Generator.cs
- unity/Assets/Puerts/Src/Resources/puerts/timer.js.txt
- unity/general/Src/UnitTest/TimerTest.cs
> 处理 timer 的异常

- unity/Assets/Puerts/Src/Editor/DocResolver.cs
- unity/Assets/Puerts/Src/Editor/Generator.cs
- unity/Assets/Puerts/Src/Editor/Resources/puerts/templates/typing.tpl.txt
> generate doc in typing d.ts

- unreal/Puerts/Source/JsEnv/Private/JsEnv.cpp
- unreal/Puerts/Source/Puerts/Private/PuertsModule.cpp
- unreal/Puerts/Source/Puerts/Public/PuertsModule.h
- unreal/Puerts/Source/PuertsEditor/Private/PEBlueprintAsset.cpp
创建了一个 MakeSharedJsEnv 函数 在启动和 PIE结束的时候都检查是否是Debug 模式。
> [unreal]修复:https://github.com/Tencent/puerts/issues/178

- unity/Assets/Puerts/Src/JsEnv.cs
- unity/Assets/Puerts/Src/MethodReflection.cs
- unity/Assets/Puerts/Src/TypeRegister.cs
- unity/general/Src/UnitTest/UnitTest.cs
> [fix]反射模式下，struct的无参数构造函数无法调用

- unreal/Puerts/Source/DeclarationGenerator/Private/DeclarationGenerator.cpp
1. Asset collect process takes sub classes asset into account; 
2. Sanitize the typing info.
> [modify] Fix & sanitize the typing info

- unity/Assets/Puerts/Src/Resources/puerts/csharp.js.txt
扩展类覆盖父类同名方法, 调用ERROR: invalid parameter
> [unity] fix [#231]

- unreal/ReactUMG/Source/ReactDeclarationGenerator/Private/ReactDeclarationGenerator.cpp
fix https://github.com/Tencent/puerts/issues/239
> 修改 enum 导出问题，改为直接使用ue模块导出的 enum

- unreal/Puerts/Source/DeclarationGenerator/Private/DeclarationGenerator.cpp
- unreal/ReactUMG/Source/ReactDeclarationGenerator/Private/ReactDeclarationGenerator.cpp
fix https://github.com/Tencent/puerts/issues/242
一起了
https://github.com/Tencent/puerts/issues/238
> Fix namespace enum

- unreal/Puerts/Source/JsEnv/Private/Ext/ObjectExtension.cpp
- unreal/Puerts/Source/JsEnv/Public/ExtensionMethods.h
Fix android build issue with ue 4.26
> Fix android build issue with ue 4.26

- unity/Assets/Puerts/Src/Editor/Generator.cs
- unity/Assets/Puerts/Src/Editor/Resources/puerts/templates/typing.tpl.txt
修改内容较多, 无法手动调整代码, 因此上传中包含格式化修改...
> [unity] typeing生成规则优化(interface方法和字段的实现)

- unity/Assets/Puerts/Src/ArgumentHelper.cs
- unity/Assets/Puerts/Src/DataTranslate.cs
- unity/Assets/Puerts/Src/Editor/Resources/puerts/templates/type.tpl.txt
- unity/Assets/Puerts/Src/StaticTranslate.cs
This reverts commit b4fd9b0c5eecb79b7f1d76c7cd625419296613e7.
> Revert "[Unity]优化DataTranslate的委托处理函数中频繁的反射性能消耗 (#337)"

- unreal/Puerts/Source/DeclarationGenerator/Private/DeclarationGenerator.cpp
aslo add cpp. prefix to arguments
> aslo add cpp. prefix to arguments 

- unreal/ReactUMG/TypeScript/react-umg/react-umg.ts
> 修复了react-umg无法重新绑定回调函数

- unity/Assets/Puerts/Src/NativeValueApiGeneric.cs
> [unity] ArrayBuffer 增加 Count 属性

- unreal/Puerts/Source/Puerts/Private/PuertsModule.cpp
- unreal/Puerts/Source/PuertsEditor/Private/PuertsEditorModule.cpp
> 编辑器下jsenv的重置放到处理完游戏逻辑后处理

- unity/Assets/Puerts/Src/Utils.cs
1.filter override property
2.filter override method
3.filter virtual method
> [unity]fix puerts.utils

- unreal/Puerts/Source/JsEnv/JsEnv.Build.cs
> [unreal]fix version check with ue5

- unity/Assets/Puerts/Src/PuertsDLL.cs
加了 PUERTS_UNSAFE 开关，并且增加了非unsafe情况下的优化
> 修复GetStringFromNative在win平台潜在的编码转换bug并优化不必要的gc

- doc/en/unreal/faq.md
- doc/en/unreal/interact_with_uclass.md
- doc/en/unreal/manual.md
- doc/en/unreal/template_binding.md
- doc/en/unreal/vscode_debug.md
Hello!
I was very interested in learning more about puerts, but was bummed to find most of the pertinent docs were not in English. So I did a very rough job at translating the Unreal docs for my own understanding (I'm personally only interested in Unreal, but it's a good start!), and I think they're good enough to share with the community.
I will note that I don't know Chinese; I used Google Translate and then tried to infer what the intention was based off the code and context. I also added some notes to clarify that these are rough translations; I also added some inline notes of some areas of confusion of what I personally interpreted the translation to mean.
I hope they're good enough to accept the PR as I know others would love to use your tool.
> Add rough English translations to docs

- unreal/Puerts/Source/ParamDefaultValueMetas/Private/ParamDefaultValueMetasModule.cpp
> [unreal]修正当生成内容为空时InitParamDefaultMetas.inl未能保存的问题，fix #631

- unity/native_src/Src/JSEngine.cpp
> Unity插件存在内存泄露

- .github/workflows/build_unity_plugins.yml
- .github/workflows/publish.yml
顺便修复publish workflow没有正确设置依赖的问题
> [unity]automatically trigger demo workflow after publish

- doc/unity/faq.md
> 添加: 常见疑问案例

- unity/Assets/Puerts/Editor/Src/Generator/DTS.cs
> Revert "导出index.d.ts报错的问题"

- unity/Assets/Puerts/Runtime/Resources/puerts/log.mjs
specification
https://developer.mozilla.org/en-US/docs/Web/API/Console/assert
result message example was taken from google chrome browser
> [unity] console.assert support

- unreal/Puerts/Source/JsEnv/Private/JsEnvImpl.cpp
> [unreal]enum添加支持反向映射

- unreal/Puerts/Source/JsEnv/Private/DelegateWrapper.cpp
- unreal/Puerts/Source/JsEnv/Private/JsEnvImpl.cpp
- unreal/Puerts/Source/JsEnv/Private/PropertyTranslator.cpp
- unreal/Puerts/Source/JsEnv/Private/SoftObjectWrapper.cpp
- unreal/Puerts/Source/JsEnv/Private/StructWrapper.cpp
GetUObject返回的可能是Released或者nullptr，因此其他地方需要额外的判断
> GetUObject的返回值需要额外的判断

- unreal/Puerts/Source/JsEnv/JsEnv.Build.cs
- unreal/Puerts/Source/JsEnv/Private/SourceFileWatcher.cpp
- unreal/Puerts/Source/JsEnv/Public/SourceFileWatcher.h
> 修正ios的编译错误

- unreal/Puerts/Source/JsEnv/Private/JsEnvImpl.cpp
- unreal/Puerts/Source/JsEnv/Public/V8Utils.h
> 读取文件之后直接转换为ts的string，减少转码次数

- unreal/Puerts/Source/JsEnv/Private/JsEnvImpl.cpp
- unreal/Puerts/Source/JsEnv/Private/TypeScriptGeneratedClass.cpp
- unreal/Puerts/Source/JsEnv/Public/TypeScriptGeneratedClass.h
[makesureinject会把lazecalljs换成calljs,所以需要在调用之前先rebind]
> fastrebind的问题修复

- unity/native_src/CMakeLists.txt
- unity/native_src/cmake/nodejs_16/backend.json
- unity/native_src/cmake/nodejs_16/backend.rc
- unity/native_src/make.js
- unity/native_src/package-lock.json
- unity/native_src/package.json
> Revert "link static library in android nodejs_16 building"

- unity/Assets/Puerts/Editor/Resources/puerts/templates/dts.tpl.mjs
- unity/Assets/Puerts/Editor/Src/DocResolver.cs
对于注释生成，需要先生成c#的注释文档，在需要生成注释的模块的*.csproj文件中，增加一行 
```xml
<DocumentationFile>Library\CommonetDocs\xxxxxx.xml</DocumentationFile>
```
xxxxxx.xml 的名字就是csproj文件的名字
参考 xxxxxx.csproj
```xml
<PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
<DebugSymbols>true</DebugSymbols>
<DebugType>full</DebugType>
<Optimize>false</Optimize>
<OutputPath>Temp\bin\Debug\</OutputPath>
<DefineConstants></DefineConstants>
<ErrorReport>prompt</ErrorReport>
<WarningLevel>4</WarningLevel>
<NoWarn>0169</NoWarn>
<AllowUnsafeBlocks>True</AllowUnsafeBlocks>
<DocumentationFile>Library\CommonetDocs\xxxxxx.xml</DocumentationFile>
<GenerateSerializationAssemblies>Auto</GenerateSerializationAssemblies>
</PropertyGroup>
```
添加注释文档生成，也可以在VSStudio中操作，
然后在VSStudio中，右键解决方案，生成解决方案
> Unity dts注释生成

- unity/Assets/Puerts/Editor/Resources/puerts/templates/dts.tpl.mjs
- unity/Assets/Puerts/Editor/Src/DocResolver.cs
> Revert "Unity dts注释生成"

- unreal/Puerts/Source/JsEnv/Private/FunctionTranslator.cpp
是否rpc的判断应该使用func_net,因为在offline模式下，始终是local
> 修正rpc走了fastcall的问题

- unity/Assets/core/upm/Editor/Resources/puerts/templates/linkxmlgen.tpl.mjs
- unity/Assets/core/upm/Editor/Src/Generator/IL2Cpp/FileExporter.cs
- unity/Assets/core/upm/Editor/Src/Generator/IL2Cpp/UnityMenu.cs
[unity] 2.0.x link.xml生成 暂时只考虑了BindingAttribute。 感觉是不是非il2cpp的版本，也要用，而且需要加入TypingAttribute更合适？
> [unity] 2.0.x link.xml生成

- unity/native_src_il2cpp/puerts_il2cpp/Puerts_il2cpp.cpp
fix for Unity 2019
fix for debug build
> [unity] 2.0.x fix for Unity 2019

- unity/Assets/core/upm/Runtime/Resources/puerts/init_il2cpp.mjs
- unity/Assets/core/upm/Runtime/Src/IL2Cpp/JsEnv.cs
目前的思路是使用init_il2cpp.mjs文件，提供与init.mjs相同的接口
还有些接口没有做，打算先看懂之前的实现后再动手做
> [unity] 2.0.x csharp module for #1055

- unreal/Puerts/Source/JsEnv/Private/StructWrapper.cpp
function是没有getter和setter的，直接设置value就行了
> handler对function处理的问题

- doc/unity/zhcn/tutorial/module.md
- doc/unity/zhcn/tutorial/typescript.md
> [Unity]丰富文档

- unity/Assets/core/upm/Editor/Src/Generator/IL2Cpp/FileExporter.cs
- unity/Assets/core/upm/Plugins/puerts_il2cpp/Puerts_il2cpp.cpp
- unity/Assets/core/upm/Runtime/Src/IL2Cpp/NativeAPI.cs
- unity/native_src_il2cpp/Inc/V8Converter.hpp
- unity/native_src_il2cpp/Src/PesapiV8Impl.cpp
- unity/test/Src/Cases/CrossLang/CrossLangTest2.cs
- unity/test/Src/Cases/CrossLang/OptionalParametersTest.cs
- unity/test/Src/Resources/CSharpModuleTest/array_extension_test.mjs
- unity/test/unity/Assets/Scripts/Tester.cs
> [unity] v2 - 反射模式unittest修复

- unity/Assets/Puerts/Runtime/Resources/puerts/log.mjs
使用和输出效果与浏览器一致
```javascript
console.time("test");
// ...
console.timeEnd("test");
```
> 增加console.time

- unreal/Puerts/Source/JsEnv/Private/CppObjectMapper.cpp
- unreal/Puerts/Source/JsEnv/Private/JsEnvImpl.cpp
https://github.com/Tencent/puerts/issues/1203
> ue对应的bindstruct的修复

- unity/Assets/core/upm/Editor/Resources/puerts/templates/dts.tpl.mjs
- unity/Assets/core/upm/Editor/Src/Generator/DTS.cs
- unity/Assets/core/upm/Runtime/Resources/puerts/csharp.mjs
- unity/test/Src/Cases/API/ForofTest.cs
- unity/test/Src/Resources/CSharpModuleTest/forof_test.mjs
let List = $generic(System.Collections.Generic.List$1, System.Int32);
let Dictionary = $generic(System.Collections.Generic.Dictionary$2, System.String, List);
let lst = new List<number>();
for (const element of lst)
{
console.log(element)
}
let dic = new Dictionary<string, System.Collections.Generic.List$1<number>>();
for (const dicElement of dic)
{
console.log(`key = ${dicElement.Key}, ${dicElement.Value}`)
}
> feature:List & Dictionary 支持forof

- unreal/Puerts/Source/PuertsEditor/Private/PuertsEditorModule.cpp
> [Unreal]修复运行Commandlet时的崩溃问题

- doc/unreal/zhcn/faq.md
> doc: add typescript version detail information.

- unreal/Puerts/Content/JavaScript/puerts/uelazyload.js
> [UE] remove redundant property

- unreal/Puerts/Source/JsEnv/Public/Binding.hpp
构建 Linux 平台会出现 [-Werror,-Wlogical-op-parentheses] 警告
> fix: [Unreal]处理运算符优先级问题，Linux 构建会抛出 [-Werror,-Wlogical-op-parentheses] 警告

- unity/Assets/core/upm/Editor/Src/Generator/RegisterInfo.cs
C#绑定，对枚举的处理问题修复
https://github.com/Tencent/puerts/issues/1367
> C#绑定，对枚举的处理问题修复

- unreal/Puerts/Source/PuertsEditor/Private/PEBlueprintAsset.cpp
> 增加生成组件时的容器类型判断 fix #1449

- unreal/Puerts/PuertsEditor/UEMeta.ts
> Fix syntax errors in comments

- unity/cli/index.js
- unity/test/Src/TestFramework/Src/Attributes.cs
1.对于/unity/cli/index.js，对代码做了以下改动：
（1）更新了写法，修改模块的导入方式
（2）使用了异步方式执行npm，防止主线程被阻塞
（3）精简了代码，将相同步骤抽象为函数，避免重复
（4）一些其他用户友好的小改动
2.对于/unity/test/Src/TestFramework/Src/Attributes.cs，修复了消息的拼写错误
> Update index.js and Attributes.cs 

- unity/Assets/core/upm/Runtime/Src/Default/Native/PuertsDLL.cs
webgl环境下需要返回long的js函数，根据指针读取实际的返回值
> [unity] feat webgl support bigint

- unreal/Puerts/Content/JavaScript/puerts/promises.js
Merge modify from unity's implementation:
https://github.com/Tencent/puerts/commit/72773e0c007bc337cc37a01f3c4d9da55091a525
> make sure unhandledRejection() run after all microtasks

- unreal/Puerts/Source/JsEnv/Private/JsEnvImpl.cpp
issue: https://github.com/Tencent/puerts/issues/1650
> AddToDelegate 区分 SingleDeleagte 和MultipleDelegate

- unreal/Puerts/Source/JsEnv/Public/UEDataBinding.hpp
for example: `RegisterTArray(UActorComponent*)`
> let RegisterTArray support pointer element type

- unreal/Puerts/Source/JsEnv/Private/JsEnvImpl.cpp
1. actor的一些component是subobject，这种comp不应该由ts持有
2. 直接布置在场景里面的actor属于asset，这种actor所有权应该是ue
> subobject和asset还是应该由外部指定所有权

- unity/Assets/core/upm/Plugins/x86_64/libnode.so.93.meta
- unity/Assets/core/upm/Plugins/x86_64/libpuerts.so.meta
> [unity] 配置 linux 库的 meta 信息

- unreal/Puerts/Source/JsEnv/Public/UEDataBinding.hpp
5.4中TArray的RemoveAt参数发生改变, 添加条件编译进行适配
> [Unreal] 修改RegisterTArray匹配5.4参数

- unity/Assets/core/upm/Runtime/Src/PathHelper.cs
https://github.com/zombieyang/puerts_unity_webgl_demo/issues/61
> PathHelper.cs添加Preserve

- unreal/Puerts/enable_puerts_module.js
```ts
class Point {
X: number;
Y: number;
Z: number;
constructor(x: number, y: number, z: number) {
this.X = x;
this.Y = y;
this.Z = z;
}
};
let start_time = new Date().getTime();
for (let i = 0; i < 100_0000; i++) {
let p = new Point(Math.random(), Math.random(), Math.random());
}
let end_time = new Date().getTime();
console.log("Time: " + (end_time - start_time) + "ms")
```
在带着`useDefineForClassFields = true`的情况下，编译出来的js
```javascript
class Point {
X;   //  <---注意这几个字段
Y;   //  <---注意这几个字段
Z;   //  <---注意这几个字段
constructor(x, y, z) {
this.X = x;
this.Y = y;
this.Z = z;
}
}
;
let start_time = new Date().getTime();
let start_time = new Date().getTime();
for (let i = 0; i < 100_0000; i++) {
let p = new Point(Math.random(), Math.random(), Math.random());
}
let end_time = new …
```
> 绕开一个v8 9.4的优化问题，JS不生成class的成员变量声明

- unreal/Puerts/Source/DeclarationGenerator/Private/DeclarationGenerator.cpp
- unreal/Puerts/Source/JsEnv/JsEnv.Build.cs
- unreal/Puerts/Source/JsEnv/Private/JSClassRegister.cpp
- unreal/Puerts/Source/JsEnv/Private/PropertyTranslator.cpp
- unreal/Puerts/Source/JsEnv/Private/StructWrapper.cpp
- unreal/Puerts/Source/JsEnv/Public/JSClassRegister.h
讨论见 https://github.com/Tencent/puerts/discussions/1800
>  Editor Only Properties 增加_EditorOnly后缀

- unity/native_src/Src/BackendEnv.cpp
(cherry picked from commit 188cf9929d04b669cdcba9ce1b483c24b8d867e0)
> [unity] fix module memory leak for v8

- unreal/Puerts/Source/JsEnv/Public/TypeInfo.hpp
- unreal/Puerts/Source/JsEnv/Public/UEDataBinding.hpp
> [unreal]修复 TCHAR 类型生成的声明错误

- unreal/Puerts/Content/JavaScript/puerts/uelazyload.js
> Update uelazyload.js reopen #1253

- doc/unreal/en/engine_call_script.md
An update to the English version of engine_call_script.md regarding clarity and grammar
> Updated engine_call_script.md (eng)

- unreal/Puerts/Content/JavaScript/PuertsEditor/CodeAnalyze.js
- unreal/Puerts/Content/JavaScript/PuertsEditor/UEMeta.js
- unreal/Puerts/PuertsEditor/CodeAnalyze.ts
- unreal/Puerts/PuertsEditor/UEMeta.ts
fixed an inconsistency in parsing of the uproperty decorator that tripped me up for a few days...
```typescript
import * as UE from 'ue';
import { ufunction, uproperty } from 'ue';
class MyActor extends UE.Actor {
//this works with the current implementation of the uproperty decorator
//@cpp:int
@uproperty.uproperty(uproperty.EditAnywhere, uproperty.BlueprintReadWrite)
public testInt: number;
//this will fail silently!
@UE.uproperty.uproperty(uproperty.EditAnywhere, uproperty.BlueprintReadWrite)
public testFloat: number;
//this will work properly with the current implementation of the ufunction decorator
//we should use similar code for the uproperty decorator!
@UE.ufunction.umeta(ufunction.ToolTip = "Adds two numbers")
@UE.ufunction.ufunction(ufunction.BlueprintCallable, …
```
> fix-uproperty-decorator

- unity/cli/make.mjs
feat: 支持从backend.json中引入cmake define
> [unity]feat: 支持从backend.json中引入cmake define

- unity/native_src/backend-quickjs/src/v8-impl.cc
去除v8-impl.cc中对quickjs-atom.h的依赖
external runtime或者动态链接虚拟机的情况下，直接使用JS_ATOM_xxx不能确保编译选项跟宿主、动态库一致，因此应该避免这种使用方式
> [unity]feat: v8-impl去除对quickjs-atom.h的依赖

- unity/Assets/core/upm/Runtime/Src/Default/JSType/GenericDelegate.cs
> fix: 修复GeneraicDelegate.cs编译错 

- unity/native_src/CMakeLists.txt
(cherry picked from commit 53ae303c34c9169a1f38109a417f6ae2b9439d61)
> [unity]fix: 使用wolfssl时编译不过

- unreal/Puerts/Source/JsEnv/Private/Gen/FBox2D_Wrap.cpp
- unreal/Puerts/Source/JsEnv/Private/Gen/FGuid_Wrap.cpp
- unreal/Puerts/Source/JsEnv/Private/Gen/FTransform_Wrap.cpp
- unreal/Puerts/Source/JsEnv/Private/Gen/FVector2D_Wrap.cpp
- unreal/Puerts/Source/JsEnv/Private/Gen/FVector4_Wrap.cpp
- unreal/Puerts/Source/JsEnv/Private/Gen/FVector_Wrap.cpp
> 修复在ue5.1中的编译错误

- unreal/Puerts/Source/JsEnv/Private/DynamicDelegateProxy.cpp
- unreal/Puerts/Source/JsEnv/Private/DynamicDelegateProxy.h
关于：https://github.com/Tencent/puerts/issues/1667
尝试调整一下GetWorld的实现。
> 调整DynamicDelegateProxy获取所属World的实现
