Tencent/puerts

unity/Assets/Puerts/Src/Resources/puerts/timer.js.txt
unity/general/Src/UnitTest/TimerTest.cs

- 改用 `Date.now()` 替换原来的 `UnityEngine_Time.deltaTime`。
- 修改单元测试，Mock 了原来的 `Date.now()` 函数。

修复 Timer 性能问题

---

unity/Assets/Puerts/Src/GenericDelegate.cs
unity/Assets/Puerts/Src/JsEnv.cs

修复此问题：
https://github.com/chexiongsheng/puerts_unity_demo/issues/8

修复崩溃：不能在C#析构线程调用ReleaseJSFunction，延后到JSEnv的Tick中处理

---

unreal/Puerts/Source/JsEnv/Private/JSClassRegister.cpp
unreal/Puerts/Source/JsEnv/Private/V8InspectorImpl.cpp

在新的UE工程中加入puerts插件后，编译时有如下错误：
Expected JSClassRegister.h to be first header included.
Expected V8InspectorImpl.h to be first header included.

fix: Error Expected xxx.h to be first header included

---

unreal/Puerts/Content/JavaScript/puerts/modular.js

修复在一些文件中，多次导入第三方库时，报模块 undefined 的问题。

fixbug: Thirdparty module exports is empty when required in other files.

---

v8-build/android_armv7.sh
v8-build/android_armv8.sh
v8-build/android_x64.sh
v8-build/ios.sh
v8-build/ios_bitcode.sh
v8-build/macos.sh

If $GITHUB WORKSPACE is not defined on the environment variable, the script path is used.

Update v8 build script

---

unreal/Puerts/Source/PuertsEditor/Private/FileSystemOperation.cpp

(cherry picked from commit 61ebf07d9e7f7639d29a6c3b0ad2e347f3827f8b)

强制转为绝对路径，避免watch找不到文件的问题

---

unity/Assets/Puerts/Src/Editor/Generator.cs

[unity]修改Generator.AddRefType,避免递归进入死循环

---

unity/Assets/Puerts/Src/Editor/Generator.cs

配置:
``` cs
using System;
using System.Collections.Generic;
using Puerts;
[Configure]
public class PuertsConfigTest
{
[Binding]
static IEnumerable<Type> Binding
{
get
{
return new List<Type>()
{
typeof(BindingClass)
};
}
}
}
public class BindingClass
{
/**
* [ERROR] Binding类型为List<>, 后续的List<T>类型未获取Type.GetGenericArguments直接退出
*/
public List<ClassA> ClassA;
public List<ClassB> ClassB;
/**[ERROR] T参数在AddRefType中循环引用crash */
public void Method<T>(Action<T> call) where T : GenericClass<T>
{
}
}
public class ClassA { }
public class ClassB { }
public abstract class GenericClass<T> where T : GenericClass<T> { }
```

[unity] 修复: 在AddRefType中的循环引用和GenericArguments丢失

---

unreal/Puerts/Source/PuertsEditor/Private/PEBlueprintAsset.cpp

本commit用于修复：https://github.com/Tencent/puerts/issues/173
原因：每次更新蓝图生成的时候，puertsEditor实际上会删除function graph并重新建立新graph，每次建立新graph应该会导致id的改变从而让子蓝图失效。
更改：不再删除旧蓝图，而是根据旧蓝图重建function，具体操作是，删除原有的pin，再重新添加pin
测试：在UE4.24上，issue 173无法再次复现

修复TS蓝图生成时改变子蓝图覆写失效

---

unity/Assets/Puerts/Src/Resources/puerts/log.js.txt
unreal/Puerts/Content/JavaScript/puerts/log.js

由于一些数据其原型链上无 toString 方法，会导致日志输出时转换为文本时出错
增加容错处理，出错的话抛出 error 信息

处理日志输出可能导致引擎运行中

---

unreal/Puerts/Source/JsEnv/Private/JsEnv.cpp
unreal/Puerts/Source/JsEnv/Private/JsEnvImpl.h
unreal/Puerts/Source/JsEnv/Public/JsEnv.h
unreal/Puerts/Source/Puerts/Private/PuertsModule.cpp
unreal/Puerts/Source/Puerts/Private/PuertsSetting.h

WaitDebugger增加超时参数，单位为秒。如果超过时间没有调试器连接上来将放行线程避免一直处于卡死状态。
默认值为0，表示无超时处理与原有行为一致

WaitDebugger增加超时参数

---

unreal/Puerts/Source/JsEnv/Private/JsEnvImpl.cpp

不能直接将OutputPath设置为DebugPath，这个行为与LoadModule方法中的行为不一致，会导致C++/JS各自分别加载相同的module时候出现重复。
同时如果只是为了修复调试断点问题，可以尝试直接将DebugPath设置为Origin而不是用OutputPath。
https://github.com/Tencent/puerts/pull/25

尝试修复C++/JS加载相同模块出现重复的问题，并处理可能由此带来的断点失效问题

---

unreal/Puerts/Source/JsEnv/Private/JsEnvImpl.cpp
unreal/Puerts/Source/JsEnv/Private/JsEnvImpl.h

在Win64 Debug版本中，开启自动绑定模式时，FJsEnvImpl析构函数清理DelegateMap处存在崩溃，
经检查是由于UObject GC问题所致。
故采用TWeakObjectPtr对指针进行保护。

[unreal]Fix GC crash of JsEnv delegate

---

doc/unreal/manual.md
unreal/Puerts/Source/DeclarationGenerator/Private/DeclarationGenerator.cpp

增加生成TS声明文件的控制台命令：Puerts.Gen
UE5 EA版的工具栏扩展按钮目前不可用，可通过此命令替代。

[unreal]Add 'Puerts.Gen' console command

---

unity/native_src/Inc/JSFunction.h
unity/native_src/Src/JSFunction.cpp

优化JSFunction Invoke函数中频繁使用的参数vector pushback造成的性能消耗 #310

[unity]建议优化JSFunction Invoke函数参数push_back性能

---

unity/Assets/Puerts/Src/ArgumentHelper.cs
unity/Assets/Puerts/Src/PuertsDLL.cs

优化C# Wrap层中ArgumentHelper构造函数中非必要的JsValueType获取，用到时再获取，减少与c++胶水层的交互次数 #316

[unity]建议优化C# Wrap层中ArgumentHelper构造函数中非必要的JsValueType获取#316 

---

unreal/Puerts/Source/PuertsEditor/Private/PEDirectoryWatcher.cpp

修复fileVersions map与dirWatcher.OnChanged的文件路径不匹配的问题（将dirWatcher.OnChanged的文件路径由相对路径改为绝对路径）

[unreal]fix watch file path

---

unity/Assets/Puerts/Src/ArgumentHelper.cs
unity/Assets/Puerts/Src/DataTranslate.cs
unity/Assets/Puerts/Src/Editor/Resources/puerts/templates/type.tpl.txt
unity/Assets/Puerts/Src/StaticTranslate.cs

优化DataTranslate的委托处理函数中频繁的反射性能消耗，生成代码中提前判断参数类型

[Unity]优化DataTranslate的委托处理函数中频繁的反射性能消耗

---

unity/Assets/Puerts/Src/Resources/puerts/timer.js.txt

[Unity]优化timer.js中每帧timerUpdate函数中的DateNow消耗

---

doc/unreal/manual.md
unreal/Puerts/Content/JavaScript/puerts/uelazyload.js
unreal/Puerts/Source/PuertsEditor/Private/PEBlueprintAsset.cpp
unreal/Puerts/Typing/ue/puerts.d.ts

扩展现有的rpc flags，补充了对reliable rpc的支持。
已经过测试。
* 设置90%丢包率，在控制台输入：net.pktloss=90
* 分别测试添加及未添加 `rpc.FunctionFlags.FUNC_NetReliable` 标记的RPC函数，检查其是否存在因丢包而导致的未执行。

[unreal]使TS中支持Reliable RPC

---

unity/Assets/Puerts/Src/DataTranslate.cs

c# object参数 接受JsObject 对象 避免js透参c#丢失JsObject

c# object参数 接受JsObject 对象

---

unreal/Puerts/Source/JsEnv/Private/JsEnvImpl.cpp
unreal/Puerts/Source/JsEnv/Private/JsEnvImpl.h

补充信息：
1. 只有蓝图类的CDO会在后台线程加载时构造，其它对象都是在GameThread中构造的。
2. 现将这类TS蓝图CDO，在后台线程发生构造时放入Pending列表，在加载完毕回到主线程后再构造。（延迟构造）
3. 构造时（TsConstruct），如果发现TS类型尚未进行Inject，会补充Inject。（应该只发生在TS蓝图CDO的构造中）

[unreal]修正蓝图CDO构造时, 会导致v8 API暴露在多线程环境下的问题. fix #354

---

quickjs-build/include/quickjs-msvc.h
quickjs-build/quickjs/quickjs.c
unity/Assets/Puerts/Src/GenericDelegate.cs
unity/Assets/Puerts/Src/JsEnv.cs
unity/general/Src/UnitTest/UnitTest.cs
unity/native_src/Src/JSEngine.cpp
unity/native_src/Src/JSEngine_Eval.cpp

[unity]新增csharp侧ExecuteModule获取module的导出的能力。修复JSObject内存问题。添加JSObject.get

---

unreal/Puerts/Source/JsEnv/JsEnv.Build.cs

参考文档:
https://docs.unrealengine.com/4.26/en-US/ProductionPipelines/BuildTools/UnrealBuildTool/ThirdPartyLibraries/

[unreal]打包时自动移动libnode.dll到指定的位置

---

unreal/Puerts/Source/JsEnv/JsEnv.Build.cs

问题：使用 BuildGraph 构建时（例如 BuildEditorAndTools.xml），会在 Compile Task 中记录生成文件，如果在 Build.cs 中手动复制文件，会导致 Compile Task 无法识别。
修正方法：使用 RuntimeDependencies.Add() 的 重载方法，让UBT 在构建时自动复制依赖的DLL 文件

修正 JsEnv Module 在构建时，手动复制 V8 DLL 文件导致 BuildGraph 无法正确识别的问题

---

unreal/Puerts/Source/JsEnv/Private/Ext/UEExtension.cpp

运行时创建`ActorComponent`需求比较常见，所以希望将`UActorComponent::RegisterComponent()`并入puerts官方

增加常用ts接口：`UActorComponent::RegisterComponent`

---

unity/Assets/Puerts/Src/Resources/puerts/log.mjs

Adding console.trace support to Unity puerts logging.
This PR adds the stacktrace to Unity log output when calling ``console.trace`` from js
Example:

add console.trace function

---

unreal/Puerts/Source/JsEnv/Private/ContainerWrapper.cpp
unreal/Puerts/Source/JsEnv/Private/ContainerWrapper.h
unreal/Puerts/Typing/ue/puerts.d.ts

#703 #604 
`ContainerWrapper.h`去掉的private是为了解决clang格式化检查

[Unreal]容器增加GetRef接口，用于显式获取容器内元素引用

---

unity/native_src/Inc/V8Utils.h

quickjs版本的stack中没有message信息，这个改动 #682  后message就没有了。需要兼容。

Revert "抛异常的时候，会重复打印一部分内容"

---

unity/Assets/Puerts/Runtime/Src/JsEnv.cs

如下图，可以看到JsEnv.Tick每帧都会有个GC Alloc，通过此优化可避免该GC Alloc。

Fix每一帧的GC问题

---

unity/Assets/Puerts/Editor/Src/Generator/DTS.cs
unity/Assets/Puerts/Runtime/Src/JsEnv.cs

业务侧不同的程序集里可能有重名的类，增加日志以直接暴露有重名的类

导出index.d.ts报错的问题

---

unity/Assets/Puerts/Editor/Resources/puerts/templates/dts.tpl.cjs

参考文档: [typescript-类型兼容性](https://www.tslang.cn/docs/handbook/type-compatibility.html)
实际效果:

[unity] dts generate生成受保护的属性, 以保证类型不兼容性

---

unreal/Puerts/Source/JsEnv/Private/TypeScriptGeneratedClass.cpp
unreal/Puerts/Source/JsEnv/Public/TypeScriptGeneratedClass.h

当开启异步加载线程，同时创建一个uclass的两个object的时候，因为此时上一个object的construct job可能还没有执行完，此时会报一个pending construct job的错误，导致第二个object的tsconstrut不执行

开启异步加载线程之后，报pending construct job的错误

---

unity/Assets/Puerts/Editor/Resources/puerts/templates/wrapper.tpl.cjs

jsEnv.RegisterGeneralGetSet 函数签名不正确

[unity]1.4.0 struct在开启blittablecopy 时，生成器生成wrapper时，函数签名不正确

---

unity/Assets/Puerts/Runtime/Resources/puerts/csharp.mjs

如下截图, 在typescript中调用Test.Ref$1返回undefined

[unity]fix:无法访问嵌套类型中泛型

---

unreal/Puerts/Source/JsEnv/Private/FunctionTranslator.cpp
unreal/Puerts/Source/JsEnv/Private/FunctionTranslator.h
unreal/Puerts/Source/JsEnv/Private/JsEnvImpl.cpp

Fix: 修复使用 delegate 的对象频繁绑定可能引起内存非法访问崩溃的问题。

Fix delegate invoke crash

---

unreal/Puerts/Source/JsEnv/Private/JsEnvImpl.cpp

没有增加类型名之前 所有的对象在dump中显示的类型都是Object不利于内存分析
增加类型名之后能看到具体的类型并且可以索引，使用全路径名防止名称冲突

[Unreal] 生成的js类型模板增加类型名称 以便于打印堆栈dump的时候 分析

---

unity/Assets/Puerts/Editor/Resources/puerts/templates/wrapper.tpl.mjs
unity/Assets/Puerts/Runtime/Src/Translator/ArgumentHelper.cs
unity/Assets/Puerts/Runtime/Src/TypeRegister.cs
unity/general/Src/UnitTest/wrap/Puerts_UnitTest_GenericGenTest2_Wrap.cs
unity/general/Src/UnitTest/wrap/Puerts_UnitTest_MultiEnvTestA_Wrap.cs
unity/general/Src/UnitTest/wrap/Puerts_UnitTest_MultiEnvTestB_Wrap.cs
unity/general/Src/UnitTest/wrap/Puerts_UnitTest_OptionalParametersClass_Wrap.cs
unity/general/Src/UnitTest/wrap/Puerts_UnitTest_WrapperTest_Wrap.cs

性能优化主要在于减少StaticTranslate以及ArgumentHelper的使用。
但针对blittableCopy会用到的ReplaceGetSet，若是去掉StaticTranslate就无法工作了。因此非基础数据类型暂无做StaticTranslate的优化

[unity] 重构wrapper.tpl，去掉ArgumentHelper。staticwrapper下性能优化10%-20%

---

unreal/Puerts/Source/PuertsEditor/Private/PEBlueprintAsset.cpp

InName已经包含了InPath，导致每次都认为代理蓝图不存在

修正每次启动都重新gen代理蓝图的问题

---

unity/Assets/core/upm/Editor/Resources/puerts/templates/cppwrapper.tpl.mjs

[unity] 2.0.x fix for overloads of UnityEngine.Debug.Log((object, UnityEngine.Object), UnityEngine.Debug.Log((object) if link.xml reserves them.
overloads will fail because, argument check in w_vO and w_vOo will always fail, if first argument is string
this solution is kinda ugly since it generates code as "if(false) return false; "

[unity] 2.0.x fix for overloads of UnityEngine.Debug.Log

---

unity/Assets/Puerts/Runtime/Resources/puerts/cjsload.mjs

有一些node_modules的目录或子目录名会带有"."号, 导致require异常, 这里让所有目录都尝试加后缀去找module
@zombieyang

[unity] 修复searchModuleInDir无法处理带"."符号的目录名

---

unity/native_src_il2cpp/Inc/Puerts_Module.h
unity/native_src_il2cpp/Src/PesapiV8Impl.cpp

1. buff.reserve will not acturally insert elements, then buff[code_size] = '\0'; will break debugger while in debug build
2. pathForDebug variable is not initialized, will break debugger while in debug build

[unity] 2.0.x fix for debug build

---

unity/Assets/Puerts/Runtime/Src/Translator/DataTranslate.cs
unity/general/Src/UnitTest/TestClasses.cs
unity/general/Src/UnitTest/TranslatorTest/JSToCSTest.cs

[unity] csharp返回object，但是实际上是number时，JS侧得到数值无小数点的问题fix

---

unreal/Puerts/Source/JsEnv/Private/JsEnvImpl.cpp

引擎版本:5.1
调用栈:
```
[2022.12.10-13.08.03:569][266]LogWindows: Error: === Critical error: ===
[2022.12.10-13.08.03:569][266]LogWindows: Error: 
[2022.12.10-13.08.03:569][266]LogWindows: Error: Fatal error!
[2022.12.10-13.08.03:569][266]LogWindows: Error: 
[2022.12.10-13.08.03:569][266]LogWindows: Error: Unhandled Exception: 0x80000003
[2022.12.10-13.08.03:569][266]LogWindows: Error: 
[2022.12.10-13.08.03:569][266]LogWindows: Error: [Callstack] 0x00007ffb5bf860d4 v8_libbase.dll!UnknownFunction []
[2022.12.10-13.08.03:569][266]LogWindows: Error: [Callstack] 0x00007ffb5a35be83 v8.dll!UnknownFunction []
[2022.12.10-13.08.03:569][266]LogWindows: Error: [Callstack] 0x00007ffb5a32dbbe v8.dll!UnknownFunction []
[2022.12.10-13.08.03:569][266]LogWindows: Error: [Callstack] 0x00007ffb59ce448e …
```

[unreal] 修复开启THREAD_SAFE时打包会崩溃问题

---

unreal/Puerts/Source/JsEnv/Private/JsEnvImpl.cpp
unreal/Puerts/Source/JsEnv/Private/JsEnvImpl.h
unreal/Puerts/Source/JsEnv/Private/StructWrapper.cpp
unreal/Puerts/Source/JsEnv/Private/StructWrapper.h

functiontemplate会被slow cache引用，永不回收，导致一个bp被gc之后重新加载，会创建新的template产生泄露。
尝试过给functiontempllate增加no_cache的参数，发现每次GetFunction都会产生一个新的function，即便缓存该function，也会导致ts的内存显著增加，怀疑可能是newinstance对没有cache的template有特殊处理。

structwrapper的functiontemplate也重用

---

unity/Assets/core/upm/Editor/Resources/puerts/templates/extension_methods_gen.tpl.mjs
unity/Assets/core/upm/Editor/Src/Generator/IL2Cpp/FileExporter.cs
unity/Assets/core/upm/Runtime/Resources/puerts/init_il2cpp.mjs
unity/Assets/core/upm/Runtime/Src/IL2Cpp/ArrayExtension.cs
unity/Assets/core/upm/Runtime/Src/IL2Cpp/ExtensionMethodInfos_Gen_Internal.cs
unity/Assets/core/upm/Runtime/Src/IL2Cpp/JsEnv.cs
unity/Assets/core/upm/Runtime/Src/IL2Cpp/TypeUtils.cs
unity/test/Src/Resources/CSharpModuleTest/array_extension_test.mjs

+ ExtensionMethodInfos_Gen_Internal for built-in extensions
- delete extensionMethodMap
* fix array extension test case double to char conversion
* fix variadic args in init_il2cpp.mjs
- 移除了运行时生成扩展函数信息的功能

[unity] 2.0.x extension method for #1128

---

unity/Assets/core/upm/Editor/Resources/puerts/templates/cppwrapper.tpl.mjs
unity/Assets/core/upm/Runtime/Resources/puerts/init_il2cpp.mjs
unity/native_src_il2cpp/Src/Puerts.cpp
unity/test/Src/Cases/GenericTest.cs
unity/test/Src/Cases/OptionalParametersTest.cs
unity/test/Src/TestFramework/Src/Attributes.cs
unity/test/unity/Assets/Scripts/Tester.cs

修复以下问题：
1. genericMethod 传入参数时key value 传反了
2. params参数前如果有可选参数且调用时未传入该可选参数，会导致创建负数长度的数组
添加测试用例：
1. 可选参数是引用类型
2. 可选参数是struct

[unity] v2 - bug修复、用例添加

---

unreal/Puerts/Source/JsEnv/Private/StructWrapper.cpp
unreal/Puerts/Source/JsEnv/Public/V8Utils.h

fname在editor下不能保持一致
getownproperty需要遍历原型链
setter需要设置returnvalue

handler问题的修复

---

unreal/Puerts/Source/Puerts/Private/PuertsModule.cpp
unreal/Puerts/Source/Puerts/Private/PuertsSetting.h

当用户修改了 tsconfig.jon 中 compilerOptions.outDir，也就是 TypeScript 翻译出来的 JavaScript 文件路径，用户可以通过虚幻编辑器修改 Edit -> Project Settings -> Plugins -> Puerts Settings -> JavaScript Root 适配新的文件路径。
NOTE: 
1.默认路径仍然为 JavaScript
2.新的路径必须为 JavaScript 的子目录，例如 JavaScript/Runtime。

feat 增加运行时 JavaScript 路径配置

---

unreal/Puerts/Source/DeclarationGenerator/Private/DeclarationGenerator.cpp
unreal/Puerts/Source/Puerts/Private/PuertsModule.cpp

1. 修复FPaths编写错误导致编译不通过的问题;
2. 修复UE5.0.x下一处编译错误的问题;
3. 对相应文件作clang-format;

[Unreal]修复一些编译错误

---

unreal/Puerts/Source/DeclarationGenerator/Private/DeclarationGenerator.cpp
unreal/Puerts/Source/DeclarationGenerator/Public/TypeScriptDeclarationGenerator.h

修复 #1184 ，引用进来的、不在生成目录下的蓝图，使用特殊标记ASSOCIATION标记。不检查变更，只在Full模式下重新生成

增加头文件生成的依赖引入

---

unreal/Puerts/Puerts.uplugin

因为有的时候，执行js的之后，如果处于predefault，可能某些moudle还没有加载，导致无法通过反射进行访问

修改puerts的load phase到default

---

unity/Assets/core/upm/Editor/Src/DocResolver.cs

dotnet 生成 xml 文档时，针对没有参数的 method，xml 名字中不会包含括号，当前 docResolver 强制加了括号导致无法给无参数的 method 生成 d.ts 注释

fix: 修复 DocResolver 无法解析空参 method doc 的 bug

---

unity/Assets/core/upm/Runtime/Resources/puerts/log.mjs

有多个输入参数时，默认的 console.log 是用 空格 来分割的

[unity] 统一 console.log 的输出行为

---

unreal/Puerts/Content/JavaScript/puerts/modular.js

https://www.npmjs.com/package/copy-anything
https://www.npmjs.com/package/is-what
最近用到了上面俩插件，发现在配置里 `require` 和 `default` 的嵌套关系是反的，添加一下支持，这俩插件的配置如下：
```
{
"exports": {
".": {
"require": {
"types": "./dist/cjs/index.d.cts",
"default": "./dist/cjs/index.cjs"
},
"import": {
"types": "./dist/index.d.ts",
"default": "./dist/index.js"
}
}
}
}
```

[unreal] feat: 完善 esm 模块读取支持

---

unreal/Puerts/Content/JavaScript/puerts/modular.js

https://www.npmjs.com/package/@formulajs/formulajs
在require 此库时出现问题，其package.json中的exports是下面的样子：
```
"exports": {
".": {
"require": "./lib/cjs/index.cjs",
"import": "./lib/esm/index.mjs"
},
"./package.json": "./package.json"
},
```
参考pr https://github.com/Tencent/puerts/pull/1379 中的改法，又补充了下esm的处理

[unreal] fix: 修复require某些esm模块失败的问题

---

doc/unity/zhcn/faq.md

最初只是想简单试用一下Puerts，结果在找不到具体 “UsingFunc” 的示例这个问题上卡了半个小时。Google找不到任何线索，最后通过对Puerts代码全文搜索理解了用法。虽然在此之后就感受到了Puerts的性能优越性，但个人仍认为这提升了Puerts的小白入门门槛，因此特加这段代码示例。

在 faq.md 中增加 UsingFunc 的示例

---

unreal/Puerts/Source/JsEnv/Public/Binding.hpp
unreal/Puerts/Source/JsEnv/Public/UEDataBinding.hpp

undefined和null都可以传递给uobject参数，当nullptr处理

undefined和null都可以传递给uobject参数，当nullptr处理,静态绑定的construtor如果参数传递错误，应该抛异常

---

unreal/Puerts/Content/JavaScript/puerts/modular.js

bug: 在tsc下，先导入第三方库(比如axios)，再导入自己的模块代码，编译后编辑器运行，则会引发找不到模块的错误;
原因是modular.js中的isESM变量没有适时恢复

fix: fix import esm bug.

---

unreal/Puerts/Source/DeclarationGenerator/Private/DeclarationGenerator.cpp

修复RestoreBlueprintTypeDeclInfos读取的文件路径还是旧路径的问题

---

unity/Assets/core/upm/Editor/Src/Generator/DTS.cs

以下为示例C#类型:
```csharp
public class ClassA
{
public abstract class Base<T>
{
}
public class ChildA : Base<int>
{
}
public class ChildB : Base<string>
{
}
}
```
它生成的dts声明
```typescript
namespace ClassA {
class Base$1<T> extends System.Object
{
protected [__keep_incompatibility]: never;
}
class ChildA extends ClassA.ClassA.Base$1<number>
{
protected [__keep_incompatibility]: never;
public constructor ()
}
class ChildB extends ClassA.ClassA.Base$1<string>
{
protected [__keep_incompatibility]: never;
public constructor ()
}
}
```

[Unity]C#类型继承自嵌套类时, dts声明生成的父类名错误(重复的外层名称)

---

unreal/Puerts/Typing/ue/puerts.d.ts

https://github.com/Tencent/puerts/blob/0cf65226919a19c6110a5bc554b082320519d982/unreal/Puerts/Source/JsEnv/Private/ContainerWrapper.cpp#L51
看了下`void FScriptArrayWrapper::Add`的实现感觉这个接口应该是支持在ts端变参输入的，这样可以一次调用Add多个元素。
测试代码: 
```typescript
function printTArray<T>(arr: ue.TArray<T>)
{
console.log("-----Num:", arr.Num());
for(var i=0; i < arr.Num(); i++) {
console.log(i, ":", arr.Get(i));
}
}
let arr = ue.NewArray(ue.BuiltinInt);
arr.Add(...[1,2,3,4,5])
printTArray(arr);   // 5 , 1,2,3,4,5
let strArr = ue.NewArray(ue.BuiltinString);
strArr.Add(...["Hello","Puer","Ts"])
printTArray(strArr); // 3, hello puer ts
```

TArray.Add() 变参函数

---

unreal/Puerts/Content/JavaScript/puerts/uelazyload.js
unreal/Puerts/Typing/ue/puerts.d.ts

更好的支持 `for(let ... of)`语法，以及更好的支持 JS容器与UE容器之间的交互。
一个简单的测试样例
```js
import * as UE from 'ue'
{
console.log('iterateArr Test');
const arr = UE.NewArray(UE.BuiltinInt);
arr.Add(...[1, 2, 3, 4, 5, 6]);
for (const i of arr) {
console.log(i) // 1,2,3,4,5,6
}
console.log(...arr) // 1,2,3,4,5,6
const jsArray = Array.from(arr);
console.log("jsarray", jsArray) // jsarray, [1,2,3,4,5,6]
}
{
console.log('iterateArr Set');
const set = UE.NewSet(UE.BuiltinInt);
for (let i = 0; i < 10; i++) {
set.Add(i);
set.Add(i);
set.Add(i);
}
for (const i of set) {
console.log(i)
}
console.log(...set) // 0,1,2,3,4...,9
const jsArray = Array.from(set);
console.log("js from set", jsArray) // js from set, [0,1,2,3,4,5,6,7,8,9]
}
{
console.log('iterateArr Map');
const map = UE.NewMap(UE.BuiltinInt, UE.BuiltinInt);
for …
```

容器添加[Symbol.iterator]支持

---

unreal/Puerts/Source/JsEnv/Private/JsEnvImpl.cpp

Fix for: https://github.com/Tencent/puerts/issues/1539
在[puerts_unreal_demo](https://github.com/BlurryLight/puerts_unreal_demo)测试了。
- FCustomStruct通过OnWeak析构(GameThread)
- FVector是走ArrayBuffer的分支

Free POD UStruct on Worker Thread. Fix #1539

---

unreal/Puerts/Source/JsEnv/Public/UEDataBinding.hpp

replace bare v8 string conversion call with wrapper functions

---

unreal/Puerts/Source/DeclarationGenerator/Private/DeclarationGenerator.cpp

处理函数参数名去重，避免 .d.ts 文件中参数名可能冲突的问题：

[unreal] 修复 codegen .d.ts 函数参数列表可能重名的问题

---

unity/Assets/core/upm/Editor/Resources/puerts/templates/cppwrapper.tpl.mjs
unity/native_src_il2cpp/Src/Puerts.cpp

之前修改的c# extension 默认参数不传导致闪退问题，导致正常传参数时候，index被加了1，使得无法给有默认值的参数传值
https://github.com/Tencent/puerts/issues/1586

解决当extension methods默认参数有传参时，index读取不正确bug

---

unreal/Puerts/Source/JsEnv/Private/JsEnvImpl.cpp

[UE]修复window使用远程打包mac编译失败，变量重名问题

[UE]修复在windows下使用远程IOS编译，变量名重名导致的编译失败

---

unreal/Puerts/Source/JsEnv/Private/V8Utils.cpp
unreal/Puerts/Source/JsEnv/Public/V8Utils.h

关联讨论见: 
https://github.com/Tencent/puerts/discussions/1591

v8 和 UE 字符串传递默认使用 UTF16 避免编码转换

---

unreal/Puerts/Source/PuertsEditor/Private/PEDirectoryWatcher.cpp

调试过程发现编辑器下FScriptArrayPropertyTranslator每帧都在调用，有点影响调试。

 UPEDirectoryWatche 只在有文件更改的时候执行delegate

---

unreal/Puerts/Source/JsEnv/Private/V8InspectorImpl.cpp

见文档 [Include What You Use](https://docs.unrealengine.com/5.1/en-US/include-what-you-use-iwyu-for-unreal-engine-programming)，有一个强制要求是 .cpp对应的头文件 .h必须是第一个被包含的头文件。
`JSEnv.Build.cs`里没有指定是否用 `PCHUsageMode.UseExplicitOrSharedPCHs`，UBT会用当前工程的  XX.Target.cs里的配置，如果`XX.Target.CS`里指定了 `BuildSettingsVersion ≥ V2`的情况下会自动开启 `IWYU`模式。
另外一种可能改法是把 `#if UE_5_3_OR_LATER`这个宏去掉，但是不知道会不会引起其他问题。
```cs
public JsEnv(ReadOnlyTargetRules Target) : base(Target)
{
#if UE_5_3_OR_LATER
PCHUsage = PCHUsageMode.NoPCHs;
#endif
```

修复在IWYU模式下的编译报错问题

---

unreal/Puerts/Source/JsEnv/Private/JsEnvImpl.cpp

ts层调用Delegate的Clear接口内存泄露，SysObjectRetainer.Release参数无效

不必要的Reset导致内存泄露，Release传入的地址是null

---

unreal/Puerts/Content/JavaScript/puerts/uelazyload.js

发现使用静态方法始终比使用成员方法慢一些，调查以后发现每次访问 `UE.XXX`的时候都会查两次`classwrapper`内的值。
```ts
UE.TestClass.StaticAdd(1,2)
```

修复静态函数每次调用的时候会查两次对象属性

---

unreal/Puerts/Content/JavaScript/puerts/uelazyload.js
unreal/Puerts/Source/JsEnv/JsEnv.Build.cs
unreal/Puerts/Source/JsEnv/Private/JsEnvImpl.cpp
unreal/Puerts/Source/JsEnv/Private/JsEnvImpl.h
unreal/Puerts/Source/JsEnv/Private/StructWrapper.h
unreal/Puerts/Typing/puerts/index.d.ts
unreal/Puerts/Typing/ue/puerts.d.ts

主要解决uobject的outer导致的泄露问题。以animbp为例，animbp的outer是actor，假设ts不小心通过actor的tsobject持有了animbp，那么即便actor被ue标记为pendingkill，也会因为animbp还没有pendingkill，导致无法回收。
打开宏后，默认情况下，ts不会持有uobject的引用，以下三种情况除外
1. 在ts里面通过newobject创建的object，会被ts持有引用
2. cdo，uclass以及asset，会被ts持有引用
3. 在mixin中指定了ts持有引用的uobject
有的时候，newobject创建的object也不希望由ts持有引用，因此newobject增加了最后一个参数，填false即可
有时候上面三种以外的情况也会需要由ts来持有引用，比如创建材质之后，在callback里面调用，因此提供了puerts.SetJsTakeRef,但该函数的使用要慎重，需要自己确保ts能正常释放，否则还是会造成泄露

增加一个宏，允许ts不持有ueobject

---

unity/native_src/Src/JSFunction.cpp

让puer.getLastException可以拿到ExecuteModule的错误

---

unity/native_src/CMakeLists.txt
unity/native_src/Src/PuertsMultBackend.cpp

1. 优化cmake中对mult backend的判断
2. 补全CreateJSEngineWithExternalEnv实现

优化cmake中对mult backend的判断 + 补全CreateJSEngineWithExternalEnv实现

---

unity/Assets/core/upm/Runtime/Src/Default/JSType/GenericDelegate.cs
unity/Assets/core/upm/Runtime/Src/Default/JsEnv.cs
unity/Assets/core/upm/Runtime/Src/Default/Native/PuertsDLL.cs
unity/native_src/Inc/BackendEnv.h
unity/native_src/Inc/IPuertsPlugin.h
unity/native_src/Inc/JSEngine.h
unity/native_src/Src/BackendEnv.cpp
unity/native_src/Src/JSEngine.cpp
unity/native_src/Src/PluginImpl.cpp
unity/native_src/Src/Puerts.cpp
unity/native_src/Src/PuertsMultBackend.cpp

feat: 增加GetJSStackTrace api
feat: 创建GenericDelegate时记录js堆栈，在CheckLiveness失败时附带堆栈方便定位
fix: 消除CreateJSEngineWithExternalEnv中的warnning

创建GenericDelegate时记录js堆栈，在CheckLiveness失败时附带堆栈方便定位

---

unreal/Puerts/Source/CSharpParamDefaultValueMetas/CSharpParamDefaultValueMetas.cs

用C#版本的UHT生成出来的`initParamDefaultMetas.inl`里面的类和函数顺序是不定的。
这会导致每次编译都会重新编译`Jsenv`的`FunctionTranslator.cpp`，(里面有个`#include "initParamDefaultMetas.inl"`)

[UE] Generate determined default value metas

---

unreal/Puerts/Source/JsEnv/Private/Gen/GenHeaders.h
unreal/Puerts/Source/JsEnv/Public/TypeScriptGeneratedClass.h

1. 5.4.1后引擎的版本控制宏失效，手动引入包含宏定义的Version.h
2. UPackage也有相应的变化，引入头文件来确保类完整

修改支持到UE 5.4.1

---

unity/Assets/core/upm/Editor/Src/Generator/Wrapper.cs

兼容如下情况的wrapper生成
``` csharp
enum E {
A= 1,B = 2
}
void Foo(E val = (E)(-1)) {}
void Bar(E val = E.A | E.B) {}
```

兼容未定义、组合标志位的enum默认值

---

unreal/Puerts/Source/PuertsEditor/Private/PEBlueprintMetaData.cpp
unreal/Puerts/Source/PuertsEditor/Public/PEBlueprintMetaData.h

在原有代码中存在两个问题
1.错误的从蓝图生成类里获取hideCategories这个hideCategories包含了父类的和蓝图本身的实际上蓝图的hideCategories属性不应该有父类的，这会导致每次编译（ts编译也就是修改了ts文件触发的编译不是在蓝图哪里编译）都会增加父类的hideCategories到蓝图中（在父类定义hideCategories即可复现，可以查看蓝图中的class setting中的hideCategories验证）
2.从ts文件收集到的元数据会被覆盖掉（即add函数，其他使用了add函数可能也有次问题）会导致ts定义了uclass.hideCategories="testts1 testts2"并不生效（即在蓝图的class setting中不会查看到）
所以进行了修改，主要思路是只将ts中收集到的数据赋值给蓝图的hideCategories，当然这里也存在一个问题就是蓝图中定义的hideCategories会被覆盖到，但是考虑到没法做到同时兼顾ts的hideCategories和蓝图的hideCategories所以只保留了ts的（原因在于同时保留蓝图的话，蓝图中记录的hideCategories分不清是ts的还是蓝图定义的，这就会导致无法正确删除掉hideCategories）

[Unreal] Bug:解决错误的将父类的hideCategories赋值给蓝图以及错误的覆盖了ts收集到的hideCategories元数据

---

unreal/Puerts/Source/PuertsEditor/Private/PEBlueprintMetaData.cpp

现有的问题：当ts文件存在metadata时，每次触发检查编译（例如给ts文件加一个空格，或则是重新打开引擎），都会触发一次编译同时NeedSave会被设置为真         NeedSave = InMetaData->Apply(GeneratedClass, Blueprint) || NeedSave; 主要是这一行Apply永远会返回真，导致每次ts文件没有变更也会变更对应的uasset文件，进而导致版本管理有些混乱。
问题的根源：错误的对比了configname，正如puerts_decorators.d.ts文件中所说的：
/**
* @brief 
*      Load object configuration at construction time.  These flags are inherited by subclasses.
*      Class containing config properties. Usage config=ConfigName or config=inherit (inherits config name from base class).
* @deprecated
*      the blueprint is always config from its parent
*/
let config: ClassKey;
这个config标签在蓝图编译过程中会被父类的取代，也就是说这个对比实际上对比的不是这一次ts的config和上一次ts文件的config而是这一次的config和父类的config，这就导致了ts定义的和父类的不一样就会一直返回真，更何况实际上并没有用获取到的现在的ts文件定义的config给蓝图生成类赋值，也就是实际上对比是的父类和NONE（config没赋值）。 …

[unreal] Fix:移除已弃用的configname避免出现没有任何改动也会进行重新编译保存的bug

---

unreal/Puerts/Source/PuertsEditor/Private/PEBlueprintMetaData.cpp
unreal/Puerts/Source/PuertsEditor/Public/PEBlueprintMetaData.h

问题:将@uclass.umeta(uclass.DisplayName="展示名字")中的uclass.DisplayName="展示名字"整个删除，不会触发重新编译蓝图（修改内容和增加没问题）
原因：bool FPEMetaDataUtils::AddMetaData(UField* InField, TMap<FName, FString>& InMetaData) 只对收集到的metadata只做了增加和修改的检查没有处理删除的检查，导致删除metadata不会被识别为发生更改，进而导致没有重新编译
解决方法：按直觉来说应该是在这个函数增加一个检查删除的逻辑，但是该函数使用的蓝图生成类中拥有的元数据可能包含了父类和其他一些定义的元数据，如HideCategories、BlueprintType，如果还是同样的思路来比较蓝图生成类拥有的元数据和收集到的元数据，就需要移除掉这些外来的元数据（即不是在ts文件中定义的元数据），但是这样的话和引擎的耦合比较大，即需要完全查明所有不在ts文件中定义的但是在蓝图生成类中有的（还可能因为版本不同而不同），故采取了另一种方法：
考虑到编译蓝图完全依赖于蓝图类，我们可以只检查puerts本身实现的能够正确配置的元数据是否被删除了即可，即SyncClassToBlueprint这个函数中同步的那些元数据（其他不在该函数赋值的元数据，本身即使编译了也不会正确赋值到蓝图中诸如一些弃用的或者是在编译过程中会被覆盖的元数据）

[unreal]Fix:增加对Class Metadata的修改检查来修复删除元数据不会被检测为更改而不重新编译的问题

---

unreal/Puerts/Source/PuertsEditor/Private/PEBlueprintAsset.cpp
unreal/Puerts/Source/PuertsEditor/Public/PEBlueprintAsset.h

蓝图中展示变量的顺序和ts中定义的不一样，在配置值时有时候会比较麻烦，故更改

[unreal]将蓝图中显示的变量顺序与TS文件中定义的变量顺序保持一致

---

unreal/Puerts/Source/PuertsEditor/Private/PEBlueprintAsset.cpp

问题：如果在ts定义一个与父类同名的变量，编译看起来能正确通过没有报错提示，但实际上没有正确添加变量，造成排查麻烦，故增加对是否成功添加了变量的检测，并在失败时进行弹窗提示。

[unreal]:增加对未能正确添加变量的情况进行提示

---

unreal/Puerts/Source/JsEnv/Private/ContainerWrapper.cpp
unreal/Puerts/Source/JsEnv/Private/PropertyTranslator.cpp
unreal/Puerts/Source/JsEnv/Private/PropertyTranslator.h

weakproperty保存的是uclass和path
当编译蓝图的时候，可能uclass和path都没有变化，但是fproperty的指针发生了变化
因此editor下需要重新初始化

weakproperty有效的时候,可能property本身无效

---

unreal/Puerts/Source/PuertsEditor/Private/PEBlueprintAsset.cpp

[unreal] Fix: 恢复生成蓝图变量的默认Flags，与过去版本保持一致

---

unreal/Puerts/Source/JsEnv/Private/JsEnvImpl.cpp

避免JsEnv被GC的后，UDynamicDelegateProxy被GC导致的崩溃

自动生命周期Delegate的owner被GC的时候ResetJsFunction 

---

unity/Assets/core/upm/Editor/Resources/puerts/xil2cpp/Puerts_il2cpp.cpp.txt
unity/Assets/core/upm/Runtime/Src/IL2Cpp/JsEnv.cs
unity/Assets/core/upm/Runtime/Src/IL2Cpp/Native/NativeAPI.cs

1.修复退出是由于互相依赖导致的crash问题;2.当C#抛出异常是可能会导致CleanupPapiEnvRef二次执行的问题

---

unreal/Puerts/Source/JsEnv/Public/UEDataBinding.hpp

主要是转换问题
测试:
```
// 	const FGameplayTagContainer*
PUERTS_NAMESPACE::DefineClass<FAggregatorEvaluateParameters>()
.Property("SourceTags", MakeReadonlyProperty(&FAggregatorEvaluateParameters::SourceTags))
.Property("TargetTags", MakeReadonlyProperty(&FAggregatorEvaluateParameters::TargetTags))
.Register();
```

[unreal]上个提交的补充

---

unreal/Puerts/Source/CSharpParamDefaultValueMetas/CSharpParamDefaultValueMetas.ubtplugin.csproj

Read engine version from Build\Build.version instead of folder name
fix #1935

Read engine version from Build.version instead of folder name

---

unreal/Puerts/Source/DeclarationGenerator/Private/TemplateBindingGenerator.cpp

相关issues: #1970
改动前即使没有构造函数的信息也能尝试构造
改动后在声明中加入abstract，不允许ts构造，但不影响从cpp中获得

[unreal]对于原生cpp绑定，若未绑定构造函数，则在ts声明中加入abstract标记，可以在ts中尝试构造时提示报错

---

unity/Assets/core/upm/Editor/Src/Generator/Utils.cs

在使用普通dotnet项目中生成wrapper后出现了报错. 发现是历史问题, 但是目前只在unity下通过宏定义取消生成相关绑定修复了该问题.  
报错信息:

fix: 完善宏定义修复普通dotnet平台下,生成的by ref like的相关绑定代码报错.

---

unreal/Puerts/Source/JsEnv/Private/V8InspectorImpl.cpp

在连接调试器的情况下，因为没有default context，所以无法在不断点的情况下执行表达式的repr，这里补充一个default context

调试器不断点的情况下，无法执行表达式的repr的修复

---

unreal/Puerts/Source/JsEnv/Private/V8Utils.cpp

line UTF16_TO_TCHAR(*(v8::String::Value(Isolate, Value))) has two memory copy operations, one is inside v8::String::Value(), the other is FString's constructor from UTF16_TO_TCHAR's address.
```
// v8::String::Value()'s implementation
String::Value::Value(v8::Isolate* v8_isolate, v8::Local<v8::Value> obj)
: str_(nullptr), length_(0) {
if (obj.IsEmpty()) return;
i::Isolate* i_isolate = reinterpret_cast<i::Isolate*>(v8_isolate);
i::HandleScope scope(i_isolate);
Local<Context> context = v8_isolate->GetCurrentContext();
ENTER_V8_BASIC(i_isolate);
TryCatch try_catch(v8_isolate);
Local<String> str;
if (!obj->ToString(context).ToLocal(&str)) return;
length_ = str->Length();
// Allocate memory here.
str_ = i::NewArray<uint16_t>(length_ + 1);
// Copy the string content into String::Value's str_ …
```

Optimize ToFString() by reduce memory copy operation.

---

unity/Assets/webgl/upm/Cli/Javascripts~/index.js

实测在windows下会重复npm i安装，原因是因为 __dirname + “node_modules” 缺少 "/"，应该是__dirname + “/node_modules” 。 改用path.join拼接出node_modules文件夹路径

WebGL CLI/index.js 避免重复npm i

---

unity/native_src/Src/BackendEnv.cpp

fix: 修复quickjs下ClearModuleCache失效的问题

[unity]fix: 修复quickjs下ClearModuleCache失效的问题

---

unity/native_src/backend-quickjs/src/v8-impl.cc

fix: 去除ArrayBuffer::New依赖的dummybuffer，减少其造成的常驻内存残留

[unity]fix: 去除ArrayBuffer::New依赖的dummybuffer，减少其造成的常驻内存残留

---

unity/native_src/backend-quickjs/src/v8-impl.cc

外部runtime模式下，puerts销毁后其js对象由宿主虚拟机产生gc会导致访问到野ioslate指针导致奔溃

[unity]fix: 修复external runtime下V8FinalizerWrap存在野指针访问问题

---

unity/cli/cmd.mjs
unity/cli/make.mjs

增加--rebuild选项，在构建时先删除旧工程，避免构建时被cmake缓存影响

[unity]feat: 增加--rebuild选项，在构建时先删除旧工程，避免构建时被cmake缓存影响

---

unity/native_src/Inc/DataTransfer.h
unity/test/Src/Cases/CrossLang/CrossLangTest.cs

this test case will fail on il2cpp mode only, could be caused by
```cpp
FORCEINLINE static v8::Local<v8::ArrayBuffer> NewArrayBuffer(v8::Local<v8::Context> Context, void* Data, size_t DataLength)
{
return v8::ArrayBuffer_New_Without_Stl(Context->GetIsolate(), Data, DataLength); // Data not copied but referenced
}
```

test & fix: arraybuffer returned from c# should be copied

---

unreal/Puerts/Source/JsEnv/Private/JsEnvImpl.cpp
unreal/Puerts/Source/JsEnv/Private/JsEnvImpl.h

**问题原因：**
当存在两个UObject类。它们各自拥有一个Value为ScriptStruct的TMap成员变量。
```
class TestObjectA : extends UE.Object {
TestMapA!: UE.TMap<number, ScriptStructA>;
}
class TestObjectB : extends UE.Object {
TestMapB!: UE.TMap<number, ScriptStructB>;
}
```
ScriptStructA和ScriptStructB结构中又分别存在另一个Map
```
namespace Game.XXX {
class ScriptStructA{
TestMapC: TMap<number, number>;
}
}
namespace Game.YYY {
class ScriptStructB {
TestMapD: TMap<number, string>;
}
}
```
当TestObjectA对象频繁操作(增加/删除)自己的TestMapA,同时TestObjectB对象频繁操作（增加/删除）自己的TestMapB时，TestMapB中的新Value（ValueNew）可能是在TestMapA的一个已被移除的Value（ValueOld）的内存位置创建的。
如果ValueOld中的TestMapC走过UEToJs流程，则ContainerCache中会有一个此内存地址的缓存，这个缓存在ValueOld.TestMapC对应的JsObject被GC时才会清理（可能比较慢）。
如果缓存清理前，ValueNew中的TestMapD也要走UEToJs流程，就会直接将ContainerCache中对应地址缓存的JsObject（ValueOld.TestMapC）给到Js, …

fix bug: ContainerCache错误命中导致Js中获取到错误的容器对象
